### ISSUE TITLE
Add pylint for django

### ISSUE THREAD

**Issue by AriHrannar** [veritus/veritus-backend#11]
vscode is annoying me

**Comment by AriHrannar** [comment]
https://github.com/landscapeio/pylint-django

**Comment by Jarngreipr** [comment]
Put on ice until python 3.6 support is available
https://github.com/PyCQA/pylint/issues/1241

**Comment by AriHrannar** [comment]
It works with python 3.6 :) they just released it two weeks ago

I have a branch where it works :)

**Comment by AriHrannar** [comment]
Dooone
