### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Ragnar-Hardarson** [veritus/veritus-backend#13]
There is a mismatch in Python versions used

Me and @Jarngreipr  are running `Python 3.6` #8 
@AriHrannar  is running `Python 3.5`
Travis CI fails on `Python 3.6` due to PIP installs :S

### Action points
- [x] Decide on Python version
- [x] Update .travis.yml to run on Python environment
- [x] Update README with Virtualenv creation command
- [x] Fix Travis for 3.6 if version bump if decided

**Comment by Ragnar-Hardarson** [comment]
I've got a preference for new is always better.

I'd like a PR introducing Travis fixes, and enforce that contributors use `Python 3.6`

**Comment by AriHrannar** [comment]
When I run 
`virtualenv -p python3 env`
there is no python 3.6, only 3.5.

I would say that python 3.6 would be preferred as that is newer, maybe it would be best for me to look into this better since I am the odd man out!

**Comment by Jarngreipr** [comment]
@AriHrannar Try to install python3.6 rather than python3

**Comment by AriHrannar** [comment]
I actually just did that and it works now, guess 3.6 isnt preinstalled on this version of ubuntu :)

I have 3.6 up and running right now (had to install the requirements twice for some reason but whatever!)

**Comment by Jarngreipr** [comment]
Do we need to update the README or not?

**Comment by Jarngreipr** [comment]
All action points have been resolved.
