### ISSUE TITLE
Extend Case class

### ISSUE THREAD

**Issue by Jarngreipr** [veritus/veritus-backend#2]
The Case class in case_gather/models.py needs to include related case numbers
```
related_case_numbers = models.CharField(
        validators=[validate_comma_separated_integer_list])
```
It also needs to include subject numbers:
` subject_numbers = models.CommaSeparatedIntegerField()`

Functionality that needs to be implemented before this can be done:

- Case object creation needs to include related_case_numbers and subject_numbers (case_gather/services.py)

**Comment by AriHrannar** [comment]
Dont think this is relevant anymore. We can just open a new issue if this needs to be implemented
