### ISSUE TITLE
Hosting for Django and DB (Spike)

### ISSUE THREAD

**Issue by Ragnar-H** [veritus/veritus-backend#39]
The frontend is hosted in [Netlify](https://www.netlify.com/) ❤️

It be great if we could find a free/cheap hosting service for the API

@AriHrannar @Jarngreipr Do you know any hosting services? And would you be willing to spend some 💰 for a service?

Resolution of this issue would entail:
- [ ] List of suitable candidates
- [ ] Pros/cons
- [ ] Can they be integrated with our CI?
- [ ] 💸?
- [ ] Do we need to change the frontend in any way?

**Comment by Ragnar-Hardarson** [comment]
Off the top of my head I know of:
- https://aws.amazon.com/
- https://azure.microsoft.com/en-gb/ (Personal favorite, but might require some email exchanges with Microsoft)
- https://www.heroku.com/
- https://www.linode.com/ (No free plan, but very reasonable prices)

**Comment by AriHrannar** [comment]
@bjerkins is using [https://www.scaleway.com/](https://www.scaleway.com/) to host some of his stuff. 3 euros for a starter cloud

**Comment by Ragnar-Hardarson** [comment]
Dockerizing everything sounds exciting.

But if I'm realistic, I doubt I'll do it.
I've got very little experience with dockerizing a project, and I kind of just want things to run right now.

If you do decide to try it, I think you should timebox the attempt

**Comment by AriHrannar** [comment]
I agree we shouldnt do it right now. I say after we are happy with a MVP, then ill look at Docker ;)

**Comment by AriHrannar** [comment]
Current status:

I have dockerized the backend and am currently autodeploying to an Amazon instance that I have.

**Comment by Ragnar-H** [comment]
Good job 🎈🎈🎈

Does the amazing instance have a static url that can be called? 
Then it should be trivial to point the frontend to it

**Comment by AriHrannar** [comment]
I think it has a static url. Just have to be sure not to delete the instance (docker cloud does that if we shut off the stack from that side) and just pause it on amazon when we dont need it running

**Comment by Ragnar-H** [comment]
If you need a static URL then it's [Route53](https://aws.amazon.com/route53/) you should look at

**Comment by Ragnar-H** [comment]
https://veritus.adult is available
Just saying ;)

**Comment by AriHrannar** [comment]
#54 works with Amazon right now. Its using Docker-cloud, which is host independent. If we want to move away from Amazon in the future, its a few clicks away. I think we should therefore close this issue.
