### ISSUE TITLE
Update subjects in database

### ISSUE THREAD

**Issue by Jarngreipr** [veritus/veritus-backend#4]
Use case_gather/xml_parser.py/gather_cases() to add subjects to database.

The parsing functionality is already implemented by the gather_cases() function, what needs to be done is to write a function similar to case_gather/services.py/update_case_db() to update subjects in database.

Tasks:
- Write update_case_db() function.

**Comment by AriHrannar** [comment]
I think this has already been implemented as subjects are being saved in the database right now
